### ISSUE TITLE
Select/Persist linked document as Object and not Array

### ISSUE THREAD

**Issue by lbenz** [oasmobile/php-dynamodb-odm#14]
Hello,
Assume i have an entity named TestClass that is linked to an other entity named TestRelation.
When i persist a TestClass instance, the field TestRelation is empty because the odm required an array and not an object.

Is it possible to change the way it works (to add object instead of array) ?
If you look at the attachment you can see when i make a select query the testRelation field is an array, it's my main problem.

![odmoasis-relation](https://user-images.githubusercontent.com/16115791/34210492-4dd07a98-e596-11e7-81d7-fb267a98dd7b.PNG)

**Comment by lbenz** [comment]
It's solved now. I have found a way by editing hydrate() and dehydrate() method in ItemReflection class.

**Comment by no7mks** [comment]
sorry for late response. glad that you have found a solution.

Here is my point of not making object support inside Item: DynamoDB is not a relational database, and I really don't want to support relations in the architecture because this will make the whole code looking much more complicated.

And I assume your 'TestRelation' class doesn't require itself being a managed Item.

However, I can anticipate many use cases like yours, and I have the following plans in mind, and I might choose to implement one of them in the future:

- provide a post-hydrate/pre-dehydrate hook (using annotators probably)
- provide a dehydratable annotator or interface, that TestRelation will implement

I appreciate your comment and am open to further discussion on this matter.

**Comment by lbenz** [comment]
Hi, 
I don't have read the whole code. 

A simple solution could be to add new parameter to ItemManager constructor like "$manageObject", if it's set to true it will be pass to ItemReflection class and then in hydrators we could change the statement depending this new parameter. 

I forked your project and brought some simple changes : [https://github.com/lbenz/php-dynamodb-odm/commit/63c1e38297c6e6d8a5bc678d3f97ffd2fbeacfda](url)

What i'm saying above is just an idea, i don't know if it's a durable solution because it adds dependency in the code.
