### ISSUE TITLE
Auto generated id

### ISSUE THREAD

**Issue by tfe2012** [oasmobile/php-dynamodb-odm#2]
Hi, is it available autogenerated annotation for key?

**Comment by no7mks** [comment]
DynamoDB doesn't natively support any incremental ID generation. That's a big reason I didn't implement this feature. 

In practice, you generate auto-ID for a DynamoDB item using your custom logic (e.g. md5 of hostname/ip + getmypid + microtimestamp + some salt). Therefore, I suggest you add ID generation in your constructor instead of an annotation, as I can't decide which algorithm the user would like to use.

Of course, the above mentioned practice cannot prevent ID collision, if they happen to appear, which for sure is rare.

**Comment by tfe2012** [comment]
for example in java they create "@DynamoDBAutoGeneratedKey" annotation. 

You also can create you own annotation, which use uniqid(); function. It's just like a standard option.

**Comment by no7mks** [comment]
As I said, problem is not about annotation, but algorithm. Since there is no way to generate an auto-incremented ID, I believe it's better to leave ID generation to the user instead of forcing an algorithm myself.

**Comment by tfe2012** [comment]
But now you need for all new items creating code like this: 

public function __construct()
{
    $id = uniqid();
}

**Comment by tfe2012** [comment]
ok, I can create my own annotation for this. Maybe your position is correct

**Comment by no7mks** [comment]
I will consider adding custom annotation support into ItemReflection in the future release. I'm not sure if this can be easily done given the current architecture. In our own projects we use the id-generation-in-constructor method, like the one you posted.
