### ISSUE TITLE
How remove item by id

### ISSUE THREAD

**Issue by tfe2012** [oasmobile/php-dynamodb-odm#5]
Currently I see only remove($obj) method. 

Can you also add method like "removeById" ?

**Comment by no7mks** [comment]
I might implement one, taking similar arguments like get().

Note that remove by id can be implemented in two different ways:

1. get the object by id first, and remove() it
2. directly call DynamoDB delete on the given ids

I prefer the first one, because it stick to what an ODM should do (i.e., manage objects, rather than a DBAL for DynamoDB). Because of that, I guess for now it's okay just call get and then remove the fetched object from IM.

But yes, I do think a function wrapped for get-and-remove helps productivity, and I'll implement one in the future release.

**Comment by tfe2012** [comment]
But you make 2 query instead of 1. 

Thx plz add it

**Comment by no7mks** [comment]
Please note, ODM implements a UnitOfWork design, so that every item an ODM manages (that includes delete) is firstly cached until a flush() is called. If removeById() doesn't fetch the object first, the deletion will:

either execute immediately
or performed after flush() is called, but with extra work to save the IDs into repository cache (more importantly, without an item to be managed)

To conclude, neither ORM nor ODM is designed to increase code execution performance. So I would rather not violate design patterns in exchange for a tiny performance boost. If you do want to benefit the performance advantage by removing id directly, you can:

get the table from the repo, and call delete() directly.

**Comment by no7mks** [comment]
I have updated the lib with the first implementation of removeById(), and exposed the internal table client if you really want to use it.

**Comment by tfe2012** [comment]
Thx
