### ISSUE TITLE
Update if exist method

### ISSUE THREAD

**Issue by tfe2012** [oasmobile/php-dynamodb-odm#6]
then you try update exist item like this:

$this->itemManager->persist($object);
 $this->itemManager->flush();

You get error: 
"Persisting existing object"

Is it possible create method update item if exist

**Comment by no7mks** [comment]
you must have persisted the item twice to the item manager, check your code. This error message is not from DynamoDB but ODM.

However, there is conditional update. You can mark any field to be a CAS field, so that every update/persist will make sure this field is the same as it was in the database. e.g.

```php
    /**
     * @var
     * @Field(type="string", cas="enabled")
     */
    protected $version;
``` 

When creating new user, it makes sure version attribute not exists (normally this is equal to that user doesn't exist). When updating user, it makes sure the version field in DB is the same as the original value of your object (whether or not you have updated it)

**Comment by tfe2012** [comment]
Yes, I try update information about current user. 

But I did get idea, how I must do it? 


I try add $version parameter but it's doesn't help

**Comment by tfe2012** [comment]
What I need to do, if I want update current user item ?

**Comment by no7mks** [comment]
with declaration of user like below:

```php
/**
 * Class CasDemoUser
 *
 * @Item(
 *     table="cas-demo-users",
 *     primaryIndex=@Index(hash="id")
 *     )
 */

class CasDemoUser {
    /**
     * @var int
     * @Field(type="number", name="uid")
     */
    public $id = 0;
    /**
     * @var
     * @Field(type="string")
     */
    public $name;
    /**
     * @var
     * @Field(type="string", cas="enabled")
     */
    public $ver;

}
```

the following script will add a user (id = 1):
```php
$user = new CasDemoUser;
$user->id = 1;
$user->name = 'John';
$user->ver = '1';
$im->persist($user);
$im->flush();
```
Run the script above twice, and the second time will fail, because ver mismatch:

```
Oasis\Mlib\ODM\Dynamodb\Exceptions\DataConsistencyException: Item exists! type = Oasis\Mlib\ODM\Dynamodb\Ut\CasDemoUser
```

In addition, if you get the user from the item manager, and update the user in two racing script with same content:

```php
$user = $im->get(CasDemoUser::class, ['id' => 1]);
$user->name = 'Alice';
$user->ver = '2';
sleep(5); // sleep for long enough so that you are able to run two scripts at the same time
$im->flush();
```

a consistency check will fail as well, because the later script will assume it's updating user with old ver = '1', where the earlier script has already set ver to '2'

```
Oasis\Mlib\ODM\Dynamodb\Exceptions\DataConsistencyException: Item upated elsewhere! type = Oasis\Mlib\ODM\Dynamodb\Ut\CasDemoUser 
```

**Comment by no7mks** [comment]
btw, consistency check is performed agains primary index only

**Comment by tfe2012** [comment]
Thx a lot, I got your idea.

I think it would be great if you added this info to documentation

**Comment by no7mks** [comment]
well, it's already in the documentation under check-and-set section.
